@startuml
title SmartHouse Context Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml


Person(user, "User", "Пользователь SmartHouse")
System(SmartHouse, "SmartHouse System", "Система управления отоплением")

System_Ext(HeatingSystem, "Heating System", "Система отопления")


Rel(user, SmartHouse, "Включает/Выключает отопление, получает информацию о температуре в доме, редактирует параметры температуры")
Rel(SmartHouse,HeatingSystem,"По запросу отправляет информацию с датчиков, принимает значение температуры которую нужно поддерживать")

@enduml